# Generated by AI 

import argparse
import json
import re
import math
from bisect import bisect_right
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKEN = re.compile(r'/\*.*?\*/|//[^\n]*|"(?:\\.|[^"\\])*"|[{}():;,]|[^\s{}():;,"\\]+|\\', re.S)
REFERENCE_SLEW_NS = 0.020
REFERENCE_LOAD_RATIO = 4.0


def scalar(token):
    if token.startswith('"'):
        return re.sub(r'\\(["\\])', r'\1', token[1:-1])
    if re.fullmatch(r'[+-]?\d+', token):
        return int(token)
    if re.fullmatch(r'[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?', token):
        return float(token)
    return token


class Parser:
    def __init__(self, source):
        self.tokens = []
        position = 0
        for match in TOKEN.finditer(source):
            if source[position:match.start()].strip():
                raise ValueError(f"Unrecognized Liberty text near character {position}")
            position = match.end()
            token = match.group()
            if not token.startswith(('/*', '//')) and token != '\\':
                self.tokens.append(token)
        if source[position:].strip():
            raise ValueError("Unrecognized trailing Liberty text")
        self.pos = 0

    def pop(self, expected=None):
        if self.pos >= len(self.tokens):
            raise ValueError("Unexpected end of Liberty file")
        token = self.tokens[self.pos]
        self.pos += 1
        if expected is not None and token != expected:
            raise ValueError(f"Expected {expected!r}, got {token!r} at token {self.pos}")
        return token

    def until(self, end):
        values = []
        while self.pos < len(self.tokens) and self.tokens[self.pos] != end:
            values.append(self.pop())
        self.pop(end)
        return values

    def body(self, closing=False):
        result = {"attributes": {}, "complex_attributes": [], "groups": []}
        while self.pos < len(self.tokens):
            if self.tokens[self.pos] == '}':
                if not closing:
                    raise ValueError("Unexpected closing brace")
                self.pop('}')
                return result
            name = self.pop()
            delimiter = self.pop()
            if delimiter == ':':
                tokens = self.until(';')
                if not tokens:
                    raise ValueError(f"Empty attribute: {name}")
                result['attributes'][name] = scalar(tokens[0]) if len(tokens) == 1 else ' '.join(tokens)
            elif delimiter == '(':
                tokens = self.until(')')
                # Liberty group arguments and complex attributes use comma-separated scalars.
                args, part = [], []
                for token in tokens + [',']:
                    if token == ',':
                        if part:
                            args.append(scalar(part[0]) if len(part) == 1 else ' '.join(part))
                        part = []
                    else:
                        part.append(token)
                following = self.pop()
                if following == '{':
                    result['groups'].append({"type": name, "args": args, **self.body(True)})
                elif following == ';':
                    if name.startswith('index_') or name == 'values':
                        rows = [[float(v.strip()) for v in str(row).split(',')] for row in args]
                        args = rows if name == 'values' else (rows[0] if len(rows) == 1 else rows)
                    result['complex_attributes'].append({"name": name, "values": args})
                else:
                    raise ValueError(f"Expected group or complex attribute after {name}")
            else:
                raise ValueError(f"Unsupported Liberty statement: {name} {delimiter}")
        if closing:
            raise ValueError("Missing closing brace")
        return result


def interpolate_delay(table, slew, load):
    data = {item['name']: item['values'] for item in table['complex_attributes']}
    x, y, values = data['index_1'], data['index_2'], data['values']
    if (len(x) < 2 or len(y) < 2
            or any(a >= b for a, b in zip(x, x[1:]))
            or any(a >= b for a, b in zip(y, y[1:]))
            or len(values) != len(x) or any(len(row) != len(y) for row in values)):
        raise ValueError('Invalid two-dimensional delay table')
    if not x[0] <= slew <= x[-1] or not y[0] <= load <= y[-1]:
        raise ValueError(f'Reference condition outside delay table: slew={slew}, load={load}')
    i = min(bisect_right(x, slew) - 1, len(x) - 2)
    j = min(bisect_right(y, load) - 1, len(y) - 2)
    a = (slew - x[i]) / (x[i + 1] - x[i])
    b = (load - y[j]) / (y[j + 1] - y[j])
    return ((1 - a) * ((1 - b) * values[i][j] + b * values[i][j + 1])
            + a * ((1 - b) * values[i + 1][j] + b * values[i + 1][j + 1]))


def simplify_cell(group, templates):
    # This model covers ordinary single-output combinational cells only.
    if any(g['type'] in ('ff', 'latch', 'statetable') for g in group['groups']):
        return None
    pins = {str(g['args'][0]): g for g in group['groups'] if g['type'] == 'pin'}
    inputs = [n for n, p in pins.items() if p['attributes'].get('direction') == 'input']
    outputs = [n for n, p in pins.items() if p['attributes'].get('direction') == 'output']
    if not inputs or len(outputs) != 1:
        return None
    if any('three_state' in p['attributes'] for p in pins.values()):
        return None
    functions = {n: pins[n]['attributes']['function'] for n in outputs
                 if 'function' in pins[n]['attributes']}
    attributes = group['attributes']
    if len(functions) != len(outputs) or 'cell_leakage_power' not in attributes:
        return None
    caps = [pins[n]['attributes']['capacitance'] for n in inputs]
    load = REFERENCE_LOAD_RATIO * sum(caps) / len(caps)
    delays = []
    for output in outputs:
        for timing in pins[output]['groups']:
            if timing['type'] != 'timing':
                continue
            if timing['attributes'].get('timing_type', 'combinational') not in (
                    'combinational', 'combinational_rise', 'combinational_fall'):
                continue
            if not set(str(timing['attributes'].get('related_pin', '')).split()) <= set(inputs):
                raise ValueError('Delay arc refers to a non-input pin')
            for table in timing['groups']:
                if table['type'] not in ('cell_rise', 'cell_fall'):
                    continue
                template = templates.get(str(table['args'][0]), {})
                if (template.get('variable_1') != 'input_net_transition'
                        or template.get('variable_2') != 'total_output_net_capacitance'):
                    raise ValueError('Unsupported delay table axes')
                delays.append(interpolate_delay(table, REFERENCE_SLEW_NS, load))
    if not delays:
        return None
    area = attributes['area']
    power = attributes['cell_leakage_power']
    delay = max(delays)
    if any(not math.isfinite(v) or v < 0 for v in (area, power, delay)):
        raise ValueError('Invalid constant area, leakage power, or delay')
    return {
        'area': {'value': area, 'unit': 'um^2'},
        'inputs': inputs,
        'outputs': outputs,
        'functions': functions,
        'leakage_power': {'value': power, 'unit': 'nW'},
        'delay': {'value': delay, 'unit': 'ns'},
    }


def convert(path):
    document = Parser(Path(path).read_text(encoding='utf-8-sig')).body()
    libraries = [g for g in document['groups'] if g['type'] == 'library']
    if len(libraries) != 1:
        raise ValueError("Expected exactly one library group")
    library = libraries[0]
    load_unit = next((a['values'] for a in library['complex_attributes']
                      if a['name'] == 'capacitive_load_unit'), None)
    if (library['attributes'].get('time_unit') != '1ns'
            or library['attributes'].get('leakage_power_unit') != '1nW'
            or load_unit != [1, 'ff']):
        raise ValueError('This constant model requires ns, nW, and fF library units')
    templates = {str(g['args'][0]): g['attributes'] for g in library['groups']
                 if g['type'] == 'lu_table_template'}
    cells = {}
    for group in library['groups']:
        if group['type'] != 'cell':
            continue
        name = str(group['args'][0])
        if name in cells:
            raise ValueError(f"Duplicate cell: {name}")
        try:
            cell = simplify_cell(group, templates)
        except (ValueError, KeyError, IndexError) as error:
            raise ValueError(f'{name}: {error}') from error
        if cell is not None:
            cells[name] = cell
    return cells


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('input', nargs='?', type=Path, default=ROOT / 'reference/library/NangateOpenCellLibrary_typical.lib')
    parser.add_argument('-o', '--output', type=Path, default=ROOT / 'input/library.json')
    args = parser.parse_args()
    try:
        data = convert(args.input)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    except (OSError, ValueError, IndexError) as error:
        parser.exit(1, f"lib2json: {error}\n")
    print(f"Wrote {len(data)} cells to {args.output}")


if __name__ == '__main__':
    main()
